site_name: 火星笔记本
site_url: https://notebook.bluesunset.top/

nav:
  - 首页: index.md
  - 语文: 
    - 首页: LL/index.md
    - 摘抄存档: 
      - 2026年:
        - 20260320: LL/摘抄/20260320.md
    - 深度论述选择性存档:
      - 首页: LL/DT/index.md
      - 《“热肠挂住”与“冷眼看穿”——庄子的情怀》: LL/DT/“热肠挂住”与“冷眼看穿”——庄子的情怀.md
      - 《此“芯”不可代彼“心”》: LL/DT/此“芯”不可代彼“心”.md
    - 作文存档:
      - 首页: LL/C/index.md
      - 血泪为路，理想为光: LL/C/血泪为路，理想为光.md
      - 青年呼以传承，文化应以活力: LL/C/青年呼以传承，文化应以活力.md
  # - 数学:
  # - 英语:
  # - 物理:
  - 化学:
      - 首页: chem/index.md
      - 理论:
        - 物质的分类: chem/theory/物质的分类.md
      - 物质:
        - 氮:
          - 概述: chem/substance/N/index.md
          - 单质:  chem/substance/N/N2.md
          - 氧化物与酸:  chem/substance/N/NO.md
          - 氨气: chem/substance/N/NH3.md
      - 实验:
        - 氨气的喷泉实验: chem/experiment/NH3.md
# - 生物:

theme:
  name: material
  language: "zh"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
  font:
    text: "Noto Sans CJK SC"
    code: "Fira Mono"
  custom_dir: overrides

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2:
      javascript: js/mermaid.min.js

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js